### ISSUE TITLE
Support of oval Roi

### ISSUE THREAD

**Issue by nvladimus** [Jhsmit/PymageJ#1]
Hi,
It's a very good library, I find it super-useful. Is it possible to add writing of Oval Roi, and specify z-plane of a roi in a stack?
Thank you!

**Comment by Jhsmit** [comment]
Thank you for your feedback, I've added a few more ROI types in devel branch. I'll look into specifying a z-plane.

**Comment by nvladimus** [comment]
Awesome, thanks!

**Comment by Jhsmit** [comment]
In commit 459e70480ac35807a043f97d25eec7ff6787ff76 i've added the possiblity to add z,c,t-position and position informatin through the 'C_POSITION', Z_POSITION, 'T_POSITION' and 'POSITION' header entries. I've added three test methods in tests/tests.py. I had some trouble exactly testing ROIs in ImageJ which have been writtin by python, I could see the correct position information through the ROI manager but I was not 100% if it works correctly as the ROI showed up in all frames of my test movie. 

I hope to publish a new release to pypi/conda forge soon, probably after implementing python3 support.

**Comment by nvladimus** [comment]
Works great, actually. I tested writing ROIOval and setting it's Z-position in a stack by 
```
x  = y = 100
z = 10
roi_obj = ROIOval(y, x, y+10, x+10) 
roi_obj.header = {'POSITION': 10} 
with ROIEncoder('./roi1.roi', roi_obj) as roi:
        roi.write()
```
and it worked like magic when I opened it in ImageJ. Thanks a lot!
