### ISSUE TITLE
Python 2/3 support

### ISSUE THREAD

**Issue by jakirkham** [Jhsmit/PymageJ#3]
Appears the codebase supports Python 2 only. Would be nice if it supported Python 2 and Python 3.

FWICT this is a simple matter of cleaning up some `print` statements and using `print` functions from [`__future__`]( https://docs.python.org/2/library/__future__.html ) instead. Though there may be some other small changes.

**Comment by Jhsmit** [comment]
Implementing this is next on mylist, it should be relatively straightforward, however when reading variables with `struct`, in python 2 the `type` returned is `str` while python 3 returns `bytes`. However, this should be relatively straightforward to fix.

**Comment by Jhsmit** [comment]
New release support python 3 only since python 2 reached end of life.
