### ISSUE TITLE
Fixing Travis CI

### ISSUE THREAD

**Issue by jakirkham** [Jhsmit/PymageJ#4]
Not sure why this is running on Travis CI if there is no `.travis.yml`. Maybe the setting "Build only if .travis.yml is present" should be enabled on Travis CI.

**Comment by jakirkham** [comment]
Alternatively adding a simple `.travis.yml` that runs the tests could work too.

**Comment by Jhsmit** [comment]
The reason is that I've never used TravisCI before, I didnt have time yet to properly configure it. When Pymagej has python3 support I will probably look into that as it might make testing run more smoothly.

**Comment by Jhsmit** [comment]
Added .travis.yml config file, Travis is now up and working
